const books = [
    { title: "The History of the Standard Oil Company", author: "Ida Tarbell", category: "Historia / Economía" },
    { title: "La isla misteriosa", author: "Julio Verne", category: "Aventura" },
    { title: "De la Tierra a la Luna", author: "Julio Verne", category: "Ciencia Ficción" },
    { title: "Antifrágil", author: "Nassim Nicholas Taleb", category: "Filosofía / Economía" },
    { title: "El cisne negro", author: "Nassim Nicholas Taleb", category: "Filosofía / Economía" },
    { title: "Superfreakonomics", author: "Stephen J. Dubner y Steven D. Levitt", category: "Economía" },
    { title: "Las aventuras de Sherlock Holmes", author: "Arthur Conan Doyle", category: "Misterio" },
    { title: "La loca de Gandoca", author: "Anacristina Rossi", category: "Novela" },
    { title: "Gestión del desarrollo sostenible en territorios rurales: Métodos para la planificación", author: "Varios autores", category: "Desarrollo rural" },
    { title: "Lo rural es diverso: Evidencia para el caso de Costa Rica", author: "Varios autores", category: "Desarrollo rural" },
    { title: "Cultivando mejor para alimentar a todos", author: "Varios autores", category: "Agricultura" },

    { title: "The 99% Invisible City", author: "Roman Mars y Kurt Kohlstedt", category: "Diseño / Urbanismo" },
    { title: "The Name of the Wind", author: "Patrick Rothfuss", category: "Fantasía" },
    { title: "Creativity, Inc.", author: "Ed Catmull con Amy Wallace", category: "Negocios / Creatividad" },
    { title: "Alchemy: The Dark Art and Curious Science of Creating Magic in Brands, Business, and Life", author: "Rory Sutherland", category: "Marketing" },
    { title: "El fin de Mr. Y", author: "Scarlett Thomas", category: "Novela" },
    { title: "Una breve historia de casi todo", author: "Bill Bryson", category: "Divulgación científica" },
    { title: "Pensar rápido, pensar despacio", author: "Daniel Kahneman", category: "Psicología" },
    { title: "The End of Alchemy", author: "Mervyn King", category: "Economía" },
    { title: "Never Split the Difference", author: "Chris Voss con Tahl Raz", category: "Negociación" },
    { title: "El teorema Katherine", author: "John Green", category: "Novela juvenil" },

    { title: "The Wasp That Brainwashed the Caterpillar", author: "Matt Simon", category: "Divulgación científica" },
    { title: "La broma infinita", author: "David Foster Wallace", category: "Novela" },
    { title: "Piénsalo otra vez", author: "Adam Grant", category: "Psicología" },
    { title: "Integrating Food into Urban Planning", author: "Yves Cabannes y Cecilia Marocchino", category: "Urbanismo" },
    { title: "Deshaciendo errores", author: "Michael Lewis", category: "Psicología / Economía" },
    { title: "Yo contengo multitudes", author: "Ed Yong", category: "Divulgación científica" },
    { title: "Mi novia se cayó en un pozo ciego", author: "Diego Delfino", category: "Crónica" },
    { title: "Cien años de soledad", author: "Gabriel García Márquez", category: "Novela" },
    { title: "¿Existe la suerte?", author: "Nassim Nicholas Taleb", category: "Filosofía" },

    { title: "El infinito en un junco", author: "Irene Vallejo", category: "Ensayo" },
    { title: "Sustainable Food Systems for All", author: "Varios autores", category: "Sostenibilidad" },
    { title: "La democracia en América", author: "Alexis de Tocqueville", category: "Política" },
    { title: "El movimiento cooperativo en Costa Rica", author: "Óscar Aguilar Bulgarelli y Carlos Luis Fallas Monge", category: "Historia económica" },
    { title: "Momentos estelares de la humanidad", author: "Stefan Zweig", category: "Historia" },
    { title: "Anna Karenina", author: "Lev Tolstói", category: "Novela clásica" },
    { title: "Ilíada", author: "Homero", category: "Épica clásica" },
    { title: "Dioses y héroes: Leyendas de la antigüedad clásica", author: "Gustav Schwab", category: "Mitología" },
    { title: "Wild Rituals", author: "Caitlin O'Connell", category: "Naturaleza" },

    { title: "Cometas en el cielo", author: "Khaled Hosseini", category: "Novela" },
    { title: "Stillness Is the Key", author: "Ryan Holiday", category: "Filosofía / Estoicismo" },
    { title: "The Obstacle Is the Way", author: "Ryan Holiday", category: "Filosofía / Estoicismo" },
    { title: "El corazón de las tinieblas", author: "Joseph Conrad", category: "Novela clásica" },
    { title: "Decidido", author: "Robert Sapolsky", category: "Neurociencia" },
    { title: "Diferentes", author: "Frans de Waal", category: "Etología" },
    { title: "En agosto nos vemos", author: "Gabriel García Márquez", category: "Novela" },
    { title: "Humor, Seriously", author: "Jennifer Aaker y Naomi Bagdonas", category: "Negocios" },

    { title: "Una tierra prometida", author: "Barack Obama", category: "Memorias" },
    { title: "El gen", author: "Siddhartha Mukherjee", category: "Divulgación científica" },
    { title: "La transformación de la mente moderna", author: "Jonathan Haidt y Greg Lukianoff", category: "Psicología social" },
    { title: "Monje y robot", author: "Becky Chambers", category: "Ciencia ficción" },
    { title: "En deuda: Una historia alternativa de la economía", author: "David Graeber", category: "Economía / Antropología" },
    { title: "El futuro por decidir", author: "Christiana Figueres y Tom Rivett-Carnac", category: "Medio ambiente" },
    { title: "Contra el estado", author: "James C. Scott", category: "Política / Antropología" },
    { title: "The Matter with Things, Vol. II: What Then Is True?", author: "Iain McGilchrist", category: "Filosofía" },
    { title: "The Matter with Things, Vol. I: The Ways to Truth", author: "Iain McGilchrist", category: "Filosofía" },

    { title: "Material World", author: "Ed Conway", category: "Divulgación / Materiales" },
    { title: "White Hot Hate", author: "Dick Lehr", category: "Crónica / Periodismo" },
    { title: "Jerks at Work", author: "Tessa West", category: "Psicología organizacional" },
    { title: "Trabajos de mierda", author: "David Graeber", category: "Antropología" },
    { title: "El amanecer de todo: Una nueva historia de la humanidad", author: "David Graeber y David Wengrow", category: "Antropología / Historia" },
    { title: "El estrecho sendero entre deseos", author: "Patrick Rothfuss", category: "Fantasía" },
    { title: "80 Tools for Participatory Development", author: "Frans Geilfus", category: "Desarrollo participativo" },
    { title: "A Little Princess", author: "Frances Hodgson Burnett", category: "Literatura juvenil" },
    { title: "Los ensayos (Tomo I)", author: "Michel de Montaigne", category: "Ensayo clásico" },
    { title: "Los ensayos (Tomo II)", author: "Michel de Montaigne", category: "Ensayo clásico" },
    { title: "Los ensayos (Tomo III)", author: "Michel de Montaigne", category: "Ensayo clásico" },

    { title: "One Piece, vols. 1-2-3 (East Blue)", author: "Eiichiro Oda", category: "Manga" },
    { title: "One Piece, vols. 4-5-6 (East Blue)", author: "Eiichiro Oda", category: "Manga" },
    { title: "One Piece, vols. 7-8-9 (East Blue)", author: "Eiichiro Oda", category: "Manga" },
    { title: "One Piece, vols. 10-11-12 (East Blue)", author: "Eiichiro Oda", category: "Manga" },
    { title: "One Piece, vols. 13-14-15 (Baroque Works)", author: "Eiichiro Oda", category: "Manga" },
    { title: "One Piece, vols. 16-17-18 (Baroque Works)", author: "Eiichiro Oda", category: "Manga" },
    { title: "Veronika decide morir", author: "Paulo Coelho", category: "Novela" },
    { title: "Mamita Yunai", author: "Carlos Luis Fallas", category: "Novela" },
    { title: "El principito", author: "Antoine de Saint-Exupéry", category: "Literatura" },
    { title: "Don Quijote de la Mancha (I)", author: "Miguel de Cervantes", category: "Novela clásica" },
    { title: "Don Quijote de la Mancha (II)", author: "Miguel de Cervantes", category: "Novela clásica" },

    { title: "Los anarquistas", author: "Roderick Kedward", category: "Historia política" },
    { title: "Sandy: Leyendas a la tica", author: "Roger Bolaños", category: "Folclor" },
    { title: "Serpientes, venenos y ofidismo en Centroamérica", author: "Varios autores", category: "Biología" },
    { title: "Quién es quién en la pintura de Goya", author: "Pedro Jesús Fernández", category: "Arte" },
    { title: "Guía de Razonamiento Lógico Matemático", author: "AMP", category: "Matemáticas" },
    { title: "Breve historia contemporánea de Costa Rica", author: "Héctor Pérez Brignoli", category: "Historia" },
    { title: "Vita Breve: Juana de Arco", author: "Mary Gordon", category: "Biografía" },
    { title: "Mi Dios", author: "Mohandas Gandhi", category: "Espiritualidad" },
    { title: "El monje que vendió su Ferrari", author: "Robin S. Sharma", category: "Autoayuda" },
    { title: "Cómo ganar amigos e influir sobre las personas", author: "Dale Carnegie", category: "Autoayuda" },

    { title: "Memorias de un primate", author: "Robert Sapolsky", category: "Memorias / Ciencia" },
    { title: "El nombre de la rosa", author: "Umberto Eco", category: "Novela histórica" },
    { title: "Don't Sleep, There Are Snakes", author: "Daniel L. Everett", category: "Lingüística / Antropología" },
    { title: "Las ventajas de ser un marginado", author: "Stephen Chbosky", category: "Novela juvenil" },
    { title: "Todo está jodido", author: "Mark Manson", category: "Ensayo" },
    { title: "Circe", author: "Madeline Miller", category: "Mitología / Novela" },
    { title: "The Ultimate Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", category: "Ciencia ficción" },
    { title: "Gilgamesh", author: "Anónimo", category: "Épica clásica" },
    { title: "El conde de Montecristo", author: "Alejandro Dumas", category: "Novela clásica" },

    { title: "The Broken Ladder", author: "Keith Payne", category: "Psicología social" },
    { title: "Orgullo y prejuicio", author: "Jane Austen", category: "Novela clásica" },
    { title: "Las leyes del Serengeti", author: "Sean B. Carroll", category: "Biología" },
    { title: "Frankenstein", author: "Mary Shelley", category: "Novela clásica" },
    { title: "Dictadores", author: "Frank Dikötter", category: "Historia política" },
    { title: "Charlatanes", author: "Moisés Naím y Quico Toro", category: "Política" },
    { title: "La sociedad de la transparencia", author: "Byung-Chul Han", category: "Filosofía" },
    { title: "Si mi biblioteca ardiera esta noche", author: "Aldous Huxley", category: "Ensayo" },
    { title: "Cartas a Lucilio", author: "Lucio Anneo Séneca", category: "Filosofía clásica" },
    { title: "La guerra no tiene rostro de mujer", author: "Svetlana Alexiévich", category: "Crónica" },
    { title: "El lecho de Procusto", author: "Nassim Nicholas Taleb", category: "Filosofía" },
    { title: "Cuentos imprescindibles del siglo XX de América Latina", author: "Varios autores", category: "Antología" },

    { title: "How to Diagnose and Fix Everything Electronic", author: "Michael Jay Geier", category: "Electrónica" },
    { title: "El arte de no ser gobernados", author: "James C. Scott", category: "Antropología política" },
    { title: "Meditaciones", author: "Marco Aurelio", category: "Filosofía clásica" },
    { title: "Dominio", author: "Tom Holland", category: "Historia" },
    { title: "Miradas sobre la desigualdad", author: "Branko Milanović", category: "Economía" },
    { title: "Historia de Costa Rica", author: "Iván Molina y Steven Palmer", category: "Historia" },
    { title: "Hacia las estrellas", author: "Mary Robinette Kowal", category: "Ciencia ficción" },
    { title: "Matadero Cinco", author: "Kurt Vonnegut", category: "Novela" },
    { title: "Las mil y una noches (Tomo I)", author: "Anónimo", category: "Literatura clásica" },
    { title: "Las mil y una noches (Tomo II)", author: "Anónimo", category: "Literatura clásica" },

    { title: "The 48 Laws of Power", author: "Robert Greene", category: "Estrategia" },
    { title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", category: "Autoayuda" },
    { title: "The Daily Stoic", author: "Ryan Holiday y Stephen Hanselman", category: "Filosofía / Estoicismo" },
    { title: "Seres sintientes", author: "Jackie Higgins", category: "Biología" },
    { title: "Final de partida", author: "Peter Turchin", category: "Historia / Sociología" },
    { title: "Anarquía relacional", author: "JC Pérez Cortés", category: "Sociología" },
    { title: "Modos de existir", author: "James Bridle", category: "Filosofía / Tecnología" },
    { title: "Ilustración pirata", author: "David Graeber", category: "Antropología" },
    { title: "El camino a la realidad", author: "Roger Penrose", category: "Física / Matemáticas" },
    { title: "La desaparición de los rituales", author: "Byung-Chul Han", category: "Filosofía" },

    { title: "Nudge", author: "Richard H. Thaler y Cass R. Sunstein", category: "Economía conductual" },
    { title: "La revancha de los poderosos", author: "Moisés Naím", category: "Política" },
    { title: "Historia de la economía", author: "John Kenneth Galbraith", category: "Economía" },
    { title: "La disciplina marcará tu destino", author: "Ryan Holiday", category: "Filosofía / Estoicismo" },
    { title: "Mirar", author: "John Berger", category: "Arte / Ensayo" },
    { title: "Cuentos de amor, de locura y de muerte", author: "Horacio Quiroga", category: "Cuento" },
    { title: "Popol Vuh", author: "Anónimo", category: "Mitología" },
    { title: "How AI Will Change Your Life", author: "Patrick Dixon", category: "Tecnología" },
    { title: "1984", author: "George Orwell", category: "Novela distópica" },
    { title: "En busca del tiempo perdido (Tomo 1)", author: "Marcel Proust", category: "Novela clásica" },
    { title: "En busca del tiempo perdido (Tomo 2)", author: "Marcel Proust", category: "Novela clásica" },
    { title: "En busca del tiempo perdido (Tomo 3)", author: "Marcel Proust", category: "Novela clásica" },

    { title: "La crisis de la narración", author: "Byung-Chul Han", category: "Filosofía" },
    { title: "Zen en el arte del tiro con arco", author: "Eugen Herrigel", category: "Filosofía oriental" }
];
