const books = [
    { title: "The History of the Standard Oil Company", author: "Ida Tarbell", category: "Historia / Economía", coverId: 313809 },
    { title: "La isla misteriosa", author: "Julio Verne", category: "Aventura", coverId: 419656 },
    { title: "De la Tierra a la Luna", author: "Julio Verne", category: "Ciencia Ficción", coverId: 13478412 },
    { title: "Antifrágil", author: "Nassim Nicholas Taleb", category: "Filosofía / Economía", coverId: 9180157 },
    { title: "El cisne negro", author: "Nassim Nicholas Taleb", category: "Filosofía / Economía", coverId: 12344090 },
    { title: "Superfreakonomics", author: "Stephen J. Dubner y Steven D. Levitt", category: "Economía", coverId: 6304875 },
    { title: "Las aventuras de Sherlock Holmes", author: "Arthur Conan Doyle", category: "Misterio", coverId: 10547050 },
    { title: "La loca de Gandoca", author: "Anacristina Rossi", category: "Novela", coverId: 5085541 },
    { title: "Gestión del desarrollo sostenible en territorios rurales: Métodos para la planificación", author: "Varios autores", category: "Desarrollo rural" },
    { title: "Lo rural es diverso: Evidencia para el caso de Costa Rica", author: "Varios autores", category: "Desarrollo rural" },
    { title: "Cultivando mejor para alimentar a todos", author: "Varios autores", category: "Agricultura" },
    { title: "The 99% Invisible City", author: "Roman Mars y Kurt Kohlstedt", category: "Diseño / Urbanismo", coverId: 10391260 },
    { title: "The Name of the Wind", author: "Patrick Rothfuss", category: "Fantasía", coverId: 11480483 },
    { title: "Creativity, Inc.", author: "Ed Catmull con Amy Wallace", category: "Negocios / Creatividad", coverId: 13124793 },
    { title: "Alchemy: The Dark Art and Curious Science of Creating Magic in Brands, Business, and Life", author: "Rory Sutherland", category: "Marketing", coverId: 10184444 },
    { title: "El fin de Mr. Y", author: "Scarlett Thomas", category: "Novela", coverId: 14462232 },
    { title: "Una breve historia de casi todo", author: "Bill Bryson", category: "Divulgación científica", coverId: 14058009 },
    { title: "Pensar rápido, pensar despacio", author: "Daniel Kahneman", category: "Psicología", coverId: 13290711 },
    { title: "The End of Alchemy", author: "Mervyn King", category: "Economía", coverId: 8875505 },
    { title: "Never Split the Difference", author: "Chris Voss con Tahl Raz", category: "Negociación", coverId: 8365942 },
    { title: "El teorema Katherine", author: "John Green", category: "Novela juvenil", coverId: 14559681 },
    { title: "The Wasp That Brainwashed the Caterpillar", author: "Matt Simon", category: "Divulgación científica", coverId: 12818938 },
    { title: "La broma infinita", author: "David Foster Wallace", category: "Novela", coverId: 8083760 },
    { title: "Piénsalo otra vez", author: "Adam Grant", category: "Psicología", coverId: 13484415 },
    { title: "Integrating Food into Urban Planning", author: "Yves Cabannes y Cecilia Marocchino", category: "Urbanismo" },
    { title: "Deshaciendo errores", author: "Michael Lewis", category: "Psicología / Economía", coverId: 9595637 },
    { title: "Yo contengo multitudes", author: "Ed Yong", category: "Divulgación científica", coverId: 8085300 },
    { title: "Mi novia se cayó en un pozo ciego", author: "Diego Delfino", category: "Crónica" },
    { title: "Cien años de soledad", author: "Gabriel García Márquez", category: "Novela", coverId: 12627383 },
    { title: "¿Existe la suerte?", author: "Nassim Nicholas Taleb", category: "Filosofía", coverId: 12344622 },
    { title: "El infinito en un junco", author: "Irene Vallejo", category: "Ensayo", coverId: 9689877 },
    { title: "Sustainable Food Systems for All", author: "Varios autores", category: "Sostenibilidad", coverId: 14421251 },
    { title: "La democracia en América", author: "Alexis de Tocqueville", category: "Política", coverId: 13556872 },
    { title: "El movimiento cooperativo en Costa Rica", author: "Óscar Aguilar Bulgarelli y Carlos Luis Fallas Monge", category: "Historia económica" },
    { title: "Momentos estelares de la humanidad", author: "Stefan Zweig", category: "Historia", coverId: 13226425 },
    { title: "Anna Karenina", author: "Lev Tolstói", category: "Novela clásica", coverId: 12327215 },
    { title: "Ilíada", author: "Homero", category: "Épica clásica", coverId: 10540134 },
    { title: "Dioses y héroes: Leyendas de la antigüedad clásica", author: "Gustav Schwab", category: "Mitología", coverId: 997804 },
    { title: "Wild Rituals", author: "Caitlin O'Connell", category: "Naturaleza" },
    { title: "Cometas en el cielo", author: "Khaled Hosseini", category: "Novela", coverId: 12328138 },
    { title: "Stillness Is the Key", author: "Ryan Holiday", category: "Filosofía / Estoicismo", coverId: 10203119 },
    { title: "The Obstacle Is the Way", author: "Ryan Holiday", category: "Filosofía / Estoicismo", coverId: 14428233 },
    { title: "El corazón de las tinieblas", author: "Joseph Conrad", category: "Novela clásica", coverId: 12325082 },
    { title: "Decidido", author: "Robert Sapolsky", category: "Neurociencia", coverId: 14049171 },
    { title: "Diferentes", author: "Frans de Waal", category: "Etología", coverId: 14128514 },
    { title: "En agosto nos vemos", author: "Gabriel García Márquez", category: "Novela", coverId: 14636533 },
    { title: "Humor, Seriously", author: "Jennifer Aaker y Naomi Bagdonas", category: "Negocios", coverId: 10389344 },
    { title: "Una tierra prometida", author: "Barack Obama", category: "Memorias", coverId: 10449357 },
    { title: "El gen", author: "Siddhartha Mukherjee", category: "Divulgación científica", coverId: 11320163 },
    { title: "La transformación de la mente moderna", author: "Jonathan Haidt y Greg Lukianoff", category: "Psicología social", coverId: 10138103 },
    { title: "Monje y robot", author: "Becky Chambers", category: "Ciencia ficción", coverId: 10476616 },
    { title: "En deuda: Una historia alternativa de la economía", author: "David Graeber", category: "Economía / Antropología", coverId: 6299464 },
    { title: "El futuro por decidir", author: "Christiana Figueres y Tom Rivett-Carnac", category: "Medio ambiente", coverId: 9296919 },
    { title: "Contra el estado", author: "James C. Scott", category: "Política / Antropología", coverId: 10381520 },
    { title: "The Matter with Things, Vol. II: What Then Is True?", author: "Iain McGilchrist", category: "Filosofía", coverId: 13219680 },
    { title: "The Matter with Things, Vol. I: The Ways to Truth", author: "Iain McGilchrist", category: "Filosofía", coverId: 13219680 },
    { title: "Material World", author: "Ed Conway", category: "Divulgación / Materiales", coverId: 14591884 },
    { title: "White Hot Hate", author: "Dick Lehr", category: "Crónica / Periodismo", coverId: 14424872 },
    { title: "Jerks at Work", author: "Tessa West", category: "Psicología organizacional", coverId: 12603134 },
    { title: "Trabajos de mierda", author: "David Graeber", category: "Antropología", coverId: 8798647 },
    { title: "El amanecer de todo: Una nueva historia de la humanidad", author: "David Graeber y David Wengrow", category: "Antropología / Historia", coverId: 11359192 },
    { title: "El estrecho sendero entre deseos", author: "Patrick Rothfuss", category: "Fantasía", coverId: 7309640 },
    { title: "80 Tools for Participatory Development", author: "Frans Geilfus", category: "Desarrollo participativo" },
    { title: "A Little Princess", author: "Frances Hodgson Burnett", category: "Literatura juvenil", coverId: 2328315 },
    { title: "Los ensayos (Tomo I)", author: "Michel de Montaigne", category: "Ensayo clásico", coverId: 13482735 },
    { title: "Los ensayos (Tomo II)", author: "Michel de Montaigne", category: "Ensayo clásico", coverId: 13482735 },
    { title: "Los ensayos (Tomo III)", author: "Michel de Montaigne", category: "Ensayo clásico", coverId: 13482735 },
    { title: "One Piece, vols. 1-2-3 (East Blue)", author: "Eiichiro Oda", category: "Manga", coverId: 1020563 },
    { title: "One Piece, vols. 4-5-6 (East Blue)", author: "Eiichiro Oda", category: "Manga", coverId: 9485994 },
    { title: "One Piece, vols. 7-8-9 (East Blue)", author: "Eiichiro Oda", category: "Manga", coverId: 1020569 },
    { title: "One Piece, vols. 10-11-12 (East Blue)", author: "Eiichiro Oda", category: "Manga", coverId: 1020698 },
    { title: "One Piece, vols. 13-14-15 (Baroque Works)", author: "Eiichiro Oda", category: "Manga", coverId: 3122735 },
    { title: "One Piece, vols. 16-17-18 (Baroque Works)", author: "Eiichiro Oda", category: "Manga", coverId: 1020703 },
    { title: "Veronika decide morir", author: "Paulo Coelho", category: "Novela", coverId: 4926517 },
    { title: "Mamita Yunai", author: "Carlos Luis Fallas", category: "Novela", coverId: 13864196 },
    { title: "El principito", author: "Antoine de Saint-Exupéry", category: "Literatura", coverId: 13499066 },
    { title: "Don Quijote de la Mancha (I)", author: "Miguel de Cervantes", category: "Novela clásica", coverId: 14428305 },
    { title: "Don Quijote de la Mancha (II)", author: "Miguel de Cervantes", category: "Novela clásica", coverId: 14428305 },
    { title: "Los anarquistas", author: "Roderick Kedward", category: "Historia política", coverId: 6383480 },
    { title: "Sandy: Leyendas a la tica", author: "Roger Bolaños", category: "Folclor" },
    { title: "Serpientes, venenos y ofidismo en Centroamérica", author: "Varios autores", category: "Biología" },
    { title: "Quién es quién en la pintura de Goya", author: "Pedro Jesús Fernández", category: "Arte", coverId: 12717205 },
    { title: "Guía de Razonamiento Lógico Matemático", author: "AMP", category: "Matemáticas" },
    { title: "Breve historia contemporánea de Costa Rica", author: "Héctor Pérez Brignoli", category: "Historia" },
    { title: "Vita Breve: Juana de Arco", author: "Mary Gordon", category: "Biografía", coverId: 1365384 },
    { title: "Mi Dios", author: "Mohandas Gandhi", category: "Espiritualidad", coverId: 3326270 },
    { title: "El monje que vendió su Ferrari", author: "Robin S. Sharma", category: "Autoayuda", coverId: 48817 },
    { title: "Cómo ganar amigos e influir sobre las personas", author: "Dale Carnegie", category: "Autoayuda", coverId: 13195013 },
    { title: "Memorias de un primate", author: "Robert Sapolsky", category: "Memorias / Ciencia", coverId: 12329605 },
    { title: "El nombre de la rosa", author: "Umberto Eco", category: "Novela histórica", coverId: 8598263 },
    { title: "Don't Sleep, There Are Snakes", author: "Daniel L. Everett", category: "Lingüística / Antropología", coverId: 9833943 },
    { title: "Las ventajas de ser un marginado", author: "Stephen Chbosky", category: "Novela juvenil", coverId: 13556024 },
    { title: "Todo está jodido", author: "Mark Manson", category: "Ensayo", coverId: 8231990 },
    { title: "Circe", author: "Madeline Miller", category: "Mitología / Novela", coverId: 8739376 },
    { title: "The Ultimate Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", category: "Ciencia ficción", coverId: 12986869 },
    { title: "Gilgamesh", author: "Anónimo", category: "Épica clásica", coverId: 474300 },
    { title: "El conde de Montecristo", author: "Alejandro Dumas", category: "Novela clásica", coverId: 14566393 },
    { title: "The Broken Ladder", author: "Keith Payne", category: "Psicología social", coverId: 8814832 },
    { title: "Orgullo y prejuicio", author: "Jane Austen", category: "Novela clásica", coverId: 13574150 },
    { title: "Las leyes del Serengeti", author: "Sean B. Carroll", category: "Biología", coverId: 8881359 },
    { title: "Frankenstein", author: "Mary Shelley", category: "Novela clásica", coverId: 12356249 },
    { title: "Dictadores", author: "Frank Dikötter", category: "Historia política", coverId: 10869587 },
    { title: "Charlatanes", author: "Moisés Naím y Quico Toro", category: "Política" },
    { title: "La sociedad de la transparencia", author: "Byung-Chul Han", category: "Filosofía", coverId: 8083811 },
    { title: "Si mi biblioteca ardiera esta noche", author: "Aldous Huxley", category: "Ensayo" },
    { title: "Cartas a Lucilio", author: "Lucio Anneo Séneca", category: "Filosofía clásica", coverId: 8256111 },
    { title: "La guerra no tiene rostro de mujer", author: "Svetlana Alexiévich", category: "Crónica", coverId: 13135723 },
    { title: "El lecho de Procusto", author: "Nassim Nicholas Taleb", category: "Filosofía", coverId: 14156240 },
    { title: "Cuentos imprescindibles del siglo XX de América Latina", author: "Varios autores", category: "Antología" },
    { title: "How to Diagnose and Fix Everything Electronic", author: "Michael Jay Geier", category: "Electrónica", coverId: 9594813 },
    { title: "El arte de no ser gobernados", author: "James C. Scott", category: "Antropología política", coverId: 6289268 },
    { title: "Meditaciones", author: "Marco Aurelio", category: "Filosofía clásica", coverId: 10469464 },
    { title: "Dominio", author: "Tom Holland", category: "Historia", coverId: 13458584 },
    { title: "Miradas sobre la desigualdad", author: "Branko Milanović", category: "Economía" },
    { title: "Historia de Costa Rica", author: "Iván Molina y Steven Palmer", category: "Historia", coverId: 12286807 },
    { title: "Hacia las estrellas", author: "Mary Robinette Kowal", category: "Ciencia ficción", coverId: 8290909 },
    { title: "Matadero Cinco", author: "Kurt Vonnegut", category: "Novela", coverId: 12727001 },
    { title: "Las mil y una noches (Tomo I)", author: "Anónimo", category: "Literatura clásica", coverId: 12339547 },
    { title: "Las mil y una noches (Tomo II)", author: "Anónimo", category: "Literatura clásica", coverId: 12339547 },
    { title: "The 48 Laws of Power", author: "Robert Greene", category: "Estrategia", coverId: 6424160 },
    { title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", category: "Autoayuda", coverId: 8231990 },
    { title: "The Daily Stoic", author: "Ryan Holiday y Stephen Hanselman", category: "Filosofía / Estoicismo", coverId: 10302294 },
    { title: "Seres sintientes", author: "Jackie Higgins", category: "Biología", coverId: 12657268 },
    { title: "Final de partida", author: "Peter Turchin", category: "Historia / Sociología", coverId: 13790624 },
    { title: "Anarquía relacional", author: "JC Pérez Cortés", category: "Sociología", coverId: 10371434 },
    { title: "Modos de existir", author: "James Bridle", category: "Filosofía / Tecnología", coverId: 14435859 },
    { title: "Ilustración pirata", author: "David Graeber", category: "Antropología", coverId: 14407897 },
    { title: "El camino a la realidad", author: "Roger Penrose", category: "Física / Matemáticas", coverId: 8427776 },
    { title: "La desaparición de los rituales", author: "Byung-Chul Han", category: "Filosofía", coverId: 13291480 },
    { title: "Nudge", author: "Richard H. Thaler y Cass R. Sunstein", category: "Economía conductual", coverId: 6402116 },
    { title: "La revancha de los poderosos", author: "Moisés Naím", category: "Política", coverId: 14250134 },
    { title: "Historia de la economía", author: "John Kenneth Galbraith", category: "Economía", coverId: 13226857 },
    { title: "La disciplina marcará tu destino", author: "Ryan Holiday", category: "Filosofía / Estoicismo", coverId: 13153179 },
    { title: "Mirar", author: "John Berger", category: "Arte / Ensayo", coverId: 13252940 },
    { title: "Cuentos de amor, de locura y de muerte", author: "Horacio Quiroga", category: "Cuento", coverId: 99816 },
    { title: "Popol Vuh", author: "Anónimo", category: "Mitología", coverId: 584099 },
    { title: "How AI Will Change Your Life", author: "Patrick Dixon", category: "Tecnología" },
    { title: "1984", author: "George Orwell", category: "Novela distópica", coverId: 14351142 },
    { title: "En busca del tiempo perdido (Tomo 1)", author: "Marcel Proust", category: "Novela clásica", coverId: 10153245 },
    { title: "En busca del tiempo perdido (Tomo 2)", author: "Marcel Proust", category: "Novela clásica", coverId: 10153245 },
    { title: "En busca del tiempo perdido (Tomo 3)", author: "Marcel Proust", category: "Novela clásica", coverId: 10153245 },
    { title: "La crisis de la narración", author: "Byung-Chul Han", category: "Filosofía", coverId: 14576033 },
    { title: "Zen en el arte del tiro con arco", author: "Eugen Herrigel", category: "Filosofía oriental", coverId: 3346542 }
];
